"""Initial migration

Revision ID: dac9169b1ea9
Revises: 
Create Date: 2025-01-12 00:14:41.190261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac9169b1ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elo', sa.String(length=15), nullable=False),
    sa.Column('user_guess', sa.String(length=50), nullable=False),
    sa.Column('correct_answer', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move')
    # ### end Alembic commands ###
